apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: users-api
        image: fcg-users-api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

        env:
        - name: ConnectionStrings__UsuariosConnection
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: connection-string

        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: jwt-key

        - name: Jwt__Issuer
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: jwt-issuer

        envFrom:
        - configMapRef:
            name: users-config