apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: default
data:
  RabbitMq__Host: "rabbitmq-service"
  ASPNETCORE_ENVIRONMENT: "Production"
---
apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: default
type: Opaque
stringData:
  # Garanta que o nome aqui combine exatamente com o que a UsersAPI lê no seu DbContext
  ConnectionStrings__UsersConnection: "Server=sqlserver-service;Database=Db_Usuarios;User Id=sa;Password=SuaSenhaForte123!;TrustServerCertificate=True;"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: fcg-users-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: users-config
        - secretRef:
            name: users-secret
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: default
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP