apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: default
type: Opaque
stringData:
  connection-string: "Server=sqlserver-service;Database=Db_Usuarios;User Id=sa;Password=SuaSenhaForte123!;TrustServerCertificate=True;"