apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: default
type: Opaque
stringData:
  connection-string: "Server=sqlserver-service;Database=Db_Usuarios;User Id=sa;Password=SuaSenhaForte123!;TrustServerCertificate=True;"
  jwt-key: "L9f2QvW8xYp3Zr6TnK1M5D7GhJ0sC4B8UeRtUyVnIqXoPaSdFgHjKlZmN2bVw=="